import { Organization, OrganizationMember, VisaCase, DemoRequest } from '@/types';

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org-atlas',
    name: 'Atlas Voyages',
    legal_name: 'Atlas Voyages SAS',
    email: 'contact@atlas-voyages.fr',
    phone: '+33 1 42 68 55 00',
    country: 'France',
    address: '14 Rue de la Paix, 75002 Paris',
    logo_url: '/logos/atlas.svg',
    status: 'ACTIVE',
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-03-15T14:30:00Z',
  },
  {
    id: 'org-salam',
    name: 'Salam Travel (Hajj & Omra)',
    legal_name: 'Salam Travel SARL',
    email: 'direction@salamtravel.fr',
    phone: '+33 4 78 90 12 34',
    country: 'France',
    address: '28 Cours Gambetta, 69007 Lyon',
    logo_url: '/logos/salam.svg',
    status: 'ACTIVE',
    created_at: '2026-02-01T10:15:00Z',
    updated_at: '2026-03-20T11:00:00Z',
  },
  {
    id: 'org-horizon',
    name: 'Horizon Travel',
    legal_name: 'Horizon Tourisme SAS',
    email: 'resa@horizontravel.fr',
    phone: '+33 4 91 22 33 44',
    country: 'France',
    address: '5 Avenue du Prado, 13006 Marseille',
    logo_url: '/logos/horizon.svg',
    status: 'ACTIVE',
    created_at: '2026-02-15T08:30:00Z',
    updated_at: '2026-03-22T16:45:00Z',
  },
];

export const INITIAL_MEMBERS: OrganizationMember[] = [
  {
    id: 'mem-1',
    organization_id: 'org-atlas',
    user_id: 'user-admin-atlas',
    name: 'Karim Mansouri',
    email: 'karim@atlas-voyages.fr',
    role: 'AGENCY_ADMIN',
    active: true,
    created_at: '2026-01-10T09:00:00Z',
  },
  {
    id: 'mem-2',
    organization_id: 'org-atlas',
    user_id: 'user-agent-atlas',
    name: 'Leila Cherif',
    email: 'leila@atlas-voyages.fr',
    role: 'AGENCY_USER',
    active: true,
    created_at: '2026-01-15T11:00:00Z',
  },
  {
    id: 'mem-3',
    organization_id: 'org-salam',
    user_id: 'user-admin-salam',
    name: 'Youssef El Amrani',
    email: 'youssef@salamtravel.fr',
    role: 'AGENCY_ADMIN',
    active: true,
    created_at: '2026-02-01T10:15:00Z',
  },
  {
    id: 'mem-super',
    organization_id: 'org-visa-gestion',
    user_id: 'user-super-admin',
    name: 'Alexandre Dumas',
    email: 'admin@visa-gestion.fr',
    role: 'SUPER_ADMIN',
    active: true,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'mem-agent',
    organization_id: 'org-visa-gestion',
    user_id: 'user-visa-agent',
    name: 'Sophie Bernard',
    email: 'sophie@visa-gestion.fr',
    role: 'VISA_AGENT',
    active: true,
    created_at: '2026-01-05T08:00:00Z',
  },
];

export const INITIAL_CASES: VisaCase[] = [
  {
    id: 'case-1',
    reference: 'VISA-2026-00125',
    organization_id: 'org-atlas',
    organization_name: 'Atlas Voyages',
    traveler_first_name: 'Sarah',
    traveler_last_name: 'Martin',
    traveler_passport_num: '24AB12345',
    traveler_nationality: 'Française',
    traveler_birth_date: '1988-06-14',
    traveler_passport_expiry: '2032-04-10',
    destination_country: 'Arabie Saoudite',
    travel_type: 'OMRA_HAJJ',
    departure_date: '2026-11-15',
    return_date: '2026-11-28',
    status: 'VISA_PRET',
    flight_pnr: 'SV8942',
    flight_company: 'Saudia',
    flight_dates: '15/11/2026 - 28/11/2026',
    assigned_agent_id: 'user-visa-agent',
    assigned_agent_name: 'Sophie Bernard',
    visa_document_url: '/mock-documents/visa_saoudite_sarah_martin.pdf',
    notes: 'Dossier validé et tampon consulaire apposé. Prêt au téléchargement.',
    created_at: '2026-09-18T14:32:00Z',
    updated_at: '2026-09-29T10:15:00Z',
    documents: [
      {
        id: 'doc-1',
        case_id: 'case-1',
        organization_id: 'org-atlas',
        type: 'PASSEPORT',
        file_name: 'passeport_sarah_martin.pdf',
        file_url: '/mock-documents/passeport.pdf',
        extracted_data: {
          first_name: 'Sarah',
          last_name: 'Martin',
          passport_number: '24AB12345',
          nationality: 'Française',
          birth_date: '1988-06-14',
          expiry_date: '2032-04-10',
          confidence: 0.98,
        },
        created_at: '2026-09-18T14:32:00Z',
      },
      {
        id: 'doc-2',
        case_id: 'case-1',
        organization_id: 'org-atlas',
        type: 'VISA_FINAL',
        file_name: 'e-visa-officiel-2026-00125.pdf',
        file_url: '/mock-documents/visa_final.pdf',
        created_at: '2026-09-29T10:15:00Z',
      },
    ],
  },
  {
    id: 'case-2',
    reference: 'VISA-2026-00126',
    organization_id: 'org-atlas',
    organization_name: 'Atlas Voyages',
    traveler_first_name: 'Ahmed',
    traveler_last_name: 'Benali',
    traveler_passport_num: '21CD98765',
    traveler_nationality: 'Française',
    traveler_birth_date: '1982-11-03',
    traveler_passport_expiry: '2029-08-22',
    destination_country: 'Ouzbékistan',
    travel_type: 'TOURISM',
    departure_date: '2026-10-20',
    return_date: '2026-11-02',
    status: 'EN_TRAITEMENT',
    flight_pnr: 'HY254',
    flight_company: 'Uzbekistan Airways',
    flight_dates: '20/10/2026 - 02/11/2026',
    assigned_agent_id: 'user-visa-agent',
    assigned_agent_name: 'Sophie Bernard',
    notes: 'Dossier transmis au service consulaire. Délai estimé 48h.',
    created_at: '2026-09-25T09:12:00Z',
    updated_at: '2026-09-28T16:00:00Z',
    documents: [
      {
        id: 'doc-3',
        case_id: 'case-2',
        organization_id: 'org-atlas',
        type: 'PASSEPORT',
        file_name: 'passeport_ahmed_benali.pdf',
        file_url: '/mock-documents/passeport.pdf',
        extracted_data: {
          first_name: 'Ahmed',
          last_name: 'Benali',
          passport_number: '21CD98765',
          nationality: 'Française',
          birth_date: '1982-11-03',
          expiry_date: '2029-08-22',
          confidence: 0.96,
        },
        created_at: '2026-09-25T09:12:00Z',
      },
    ],
  },
  {
    id: 'case-3',
    reference: 'VISA-2026-00127',
    organization_id: 'org-salam',
    organization_name: 'Salam Travel (Hajj & Omra)',
    traveler_first_name: 'Mohamed',
    traveler_last_name: 'Khelifi',
    traveler_passport_num: '19EF45678',
    traveler_nationality: 'Française',
    traveler_birth_date: '1975-04-20',
    traveler_passport_expiry: '2030-01-15',
    destination_country: 'Arabie Saoudite',
    travel_type: 'OMRA_HAJJ',
    departure_date: '2026-12-01',
    return_date: '2026-12-15',
    status: 'PRET_A_TRANSMETTRE',
    flight_pnr: 'SV142',
    flight_company: 'Saudia',
    assigned_agent_id: 'user-visa-agent',
    assigned_agent_name: 'Sophie Bernard',
    notes: 'Contrôle conformité IA effectué avec succès. Prêt à soumettre au consulat.',
    created_at: '2026-09-27T11:45:00Z',
    updated_at: '2026-09-29T08:30:00Z',
  },
  {
    id: 'case-4',
    reference: 'VISA-2026-00128',
    organization_id: 'org-atlas',
    organization_name: 'Atlas Voyages',
    traveler_first_name: 'Camille',
    traveler_last_name: 'Dupont',
    traveler_passport_num: '23GH33445',
    traveler_nationality: 'Française',
    traveler_birth_date: '1995-09-19',
    traveler_passport_expiry: '2033-07-01',
    destination_country: 'Chine',
    travel_type: 'BUSINESS',
    departure_date: '2026-11-05',
    return_date: '2026-11-18',
    status: 'A_VERIFIER',
    notes: 'Nouvelle demande déposée par l agence. Pièce d identité reçue, en attente de vérification des dates.',
    created_at: '2026-09-30T10:00:00Z',
    updated_at: '2026-09-30T10:00:00Z',
  },
];

export const INITIAL_DEMO_REQUESTS: DemoRequest[] = [
  {
    id: 'demo-1',
    first_name: 'Marc',
    last_name: 'Lemoine',
    agency_name: 'Évasion Tourisme',
    professional_email: 'm.lemoine@evasion-tourisme.fr',
    phone: '+33 1 55 44 33 22',
    country: 'France',
    monthly_volume: '50 à 100 visas / mois',
    message: 'Nous souhaitons arrêter d échanger les passeports par WhatsApp.',
    status: 'NEW',
    created_at: '2026-09-30T15:20:00Z',
  },
];
